### ISSUE TITLE
UI version does not work because of internal path mismatch

### ISSUE THREAD

**Issue by qooban** [edk-software/edk-route-verifier#133]
edk-route-verifier started in UI flavour throws the following error:
```
Started serving Verify API and static content at http://localhost:9102.

Error: Failed to lookup view "pages/index" in views directory "/usr/local/lib/node_modules/edk-route-verifier/conf/src/server"

    at Function.render (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/application.js:580:17)

    at ServerResponse.render (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/response.js:1012:7)

    at file:///usr/local/lib/node_modules/edk-route-verifier/src/server/uiRoutes.js:45:13

    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/layer.js:95:5)

    at next (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/route.js:137:13)

    at Route.dispatch (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/route.js:112:3)

    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/layer.js:95:5)

    at /usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/index.js:281:22

    at param (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/index.js:354:14)

    at param (/usr/local/lib/node_modules/edk-route-verifier/node_modules/express/lib/router/index.js:365:14)
```

**Comment by qooban** [comment]
Part of the solution: https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-when-using-the-experimental-modules-flag
